
services:
  db:
    image: mysql:8.0
    container_name: mysql_rua
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql # Usa un named volume
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: "1.0"  # Máximo 1 núcleo
          memory: "700M"  # Máximo 700MB de RAM
        reservations:
          cpus: "0.5"
          memory: "400M"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"  # phpMyAdmin estará disponible en el puerto 8080
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      UPLOAD_LIMIT: 100M  # Opcional, para ajustar el límite de subida de archivos
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "200M"
        reservations:
          cpus: "0.1"
          memory: "100M"

networks:
  app-network:
    name: app-network
    driver: bridge

volumes:
  mysql_data:
