version: '3.8'

services:
  cbasb_api:
    container_name: cbasb_api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    volumes:
      - .:/workdir
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=America/Argentina/Cordoba
      - PYTHONPATH=/workdir/src
    networks:
      - app-network
    working_dir: /workdir
    command: >
      uvicorn src.main:api --host 0.0.0.0 --port 8002 --reload

  mysql:
    image: mysql:8.0
    container_name: mysql_rua
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=po02025
      - MYSQL_DATABASE=tp2
      - MYSQL_USER=usertp2
      - MYSQL_PASSWORD=po02025
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:

